const expenses = [
  {"description":"Electricity",      "amount":"125.55","type":"expenses","repetition":"recurring","date":"2020-01-10"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2020-01-23"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2020-01-23"},
  {"description":"Cinema",                "amount":"45.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-01-23"},
  {"description":"Month Food",        "amount":"625.78","type":"expenses","repetition":"recurring","date":"2020-01-23"},
  {"description":"Clothes","amount":"150.99","type":"expenses","repetition":"nonRecurring",  "date":"2020-01-26"},
  {"description":"Car fix","amount":"90.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-01-23"},
  {"description":"Pizza",                 "amount":"60.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-01-19"},
  {"description":"ReactJS Book",     "amount":"85.95", "type":"expenses","repetition":"nonRecurring",  "date":"2020-01-13"},
  {"description":"Hamburger",                "amount":"45.70", "type":"expenses","repetition":"nonRecurring",  "date":"2020-01-23"},
  {"description":"Water Bill",                  "amount":"75.55", "type":"expenses","repetition":"recurring","date":"2020-01-15"},

  {"description":"Car fix","amount":"20.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-02-23"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2020-02-23"},
  {"description":"Pizza",                 "amount":"40.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-02-19"},
  {"description":"Electricity",      "amount":"112.55","type":"expenses","repetition":"recurring","date":"2020-02-10"},
  {"description":"ReactJS Book",     "amount":"45.95", "type":"expenses","repetition":"nonRecurring",  "date":"2020-02-13"},
  {"description":"Water Bill",                  "amount":"43.55", "type":"expenses","repetition":"recurring","date":"2020-02-15"},
  {"description":"Clothes","amount":"130.99","type":"expenses","repetition":"nonRecurring",  "date":"2020-02-26"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2020-02-23"},
  {"description":"Hamburger",                "amount":"35.70", "type":"expenses","repetition":"nonRecurring",  "date":"2020-02-23"},
  {"description":"Month Food",        "amount":"525.78","type":"expenses","repetition":"recurring","date":"2020-02-23"},
  {"description":"Cinema",                "amount":"80.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-02-23"},
  
  {"description":"IPhone",                "amount":"1499.70", "type":"expenses","repetition":"nonRecurring",  "date":"2020-03-23"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2020-03-23"},
  {"description":"Electricity",      "amount":"112.55","type":"expenses","repetition":"recurring","date":"2020-03-10"},
  {"description":"Pizza",                 "amount":"50.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-03-19"},
  {"description":"Car fix","amount":"20.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-03-23"},
  {"description":"Clothes","amount":"130.99","type":"expenses","repetition":"nonRecurring",  "date":"2020-03-26"},
  {"description":"Water Bill",                  "amount":"43.55", "type":"expenses","repetition":"recurring","date":"2020-03-15"},
  {"description":"Cinema",                "amount":"80.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-03-23"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2020-03-23"},
  {"description":"ReactJS Book",     "amount":"45.95", "type":"expenses","repetition":"nonRecurring",  "date":"2020-03-13"},
  {"description":"Hamburger",                "amount":"35.70", "type":"expenses","repetition":"nonRecurring",  "date":"2020-03-23"},
  {"description":"Month Food",        "amount":"525.78","type":"expenses","repetition":"recurring","date":"2020-03-23"},
  
  {"description":"Electricity",      "amount":"142.55","type":"expenses","repetition":"recurring","date":"2020-04-10"},
  {"description":"Pizza",                 "amount":"40.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-04-19"},
  {"description": "Phone Bill",             "amount":"111.99", "type":"expenses","repetition":"recurring","date":"2020-04-23"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2020-04-23"},
  {"description":"Car fix","amount":"220.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-04-23"},
  {"description":"Month Food",        "amount":"529.78","type":"expenses","repetition":"recurring","date":"2020-04-23"},
  {"description":"Water Bill",                  "amount":"63.55", "type":"expenses","repetition":"recurring","date":"2020-04-15"},
  {"description":"Cinema",                "amount":"60.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-04-23"},
  {"description":"Hamburger",                "amount":"75.70", "type":"expenses","repetition":"nonRecurring",  "date":"2020-04-23"},
  {"description":"ReactJS Book",     "amount":"65.95", "type":"expenses","repetition":"nonRecurring",  "date":"2020-04-13"},
  {"description":"Clothes","amount":"170.99","type":"expenses","repetition":"nonRecurring",  "date":"2020-04-26"},
  
  {"description":"Water Bill",                  "amount":"73.55", "type":"expenses","repetition":"recurring","date":"2020-05-15"},
  {"description":"Electricity",      "amount":"212.55","type":"expenses","repetition":"recurring","date":"2020-05-10"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2020-05-23"},
  {"description":"Pizza",                 "amount":"120.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-05-19"},
  {"description":"Month Food",        "amount":"520.78","type":"expenses","repetition":"recurring","date":"2020-05-23"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2020-05-23"},
  {"description":"Car fix","amount":"120.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-05-23"},
  {"description":"Cinema",                "amount":"180.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-05-23"},
  {"description":"Hamburger",                "amount":"75.70", "type":"expenses","repetition":"nonRecurring",  "date":"2020-05-23"},
  {"description":"ReactJS Book",     "amount":"25.95", "type":"expenses","repetition":"nonRecurring",  "date":"2020-05-13"},
  {"description":"Clothes","amount":"180.99","type":"expenses","repetition":"nonRecurring",  "date":"2020-05-26"},
  
  {"description":"Cinema",                "amount":"80.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-06-23"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2020-06-23"},
  {"description":"Pizza",                 "amount":"40.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-06-19"},
  {"description":"Electricity",      "amount":"162.55","type":"expenses","repetition":"recurring","date":"2020-06-10"},
  {"description":"Water Bill",                  "amount":"43.55", "type":"expenses","repetition":"recurring","date":"2020-06-15"},
  {"description":"Clothes","amount":"130.99","type":"expenses","repetition":"nonRecurring",  "date":"2020-06-26"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2020-06-23"},
  {"description":"Month Food",        "amount":"485.78","type":"expenses","repetition":"recurring","date":"2020-06-23"},
  {"description":"Trip",                "amount":"1235.70", "type":"expenses","repetition":"nonRecurring",  "date":"2020-06-23"},
  {"description":"Car fix","amount":"120.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-06-23"},
  {"description":"Hamburger",                "amount":"35.70", "type":"expenses","repetition":"nonRecurring",  "date":"2020-06-23"},
  {"description":"ReactJS Book",     "amount":"25.95", "type":"expenses","repetition":"nonRecurring",  "date":"2020-06-13"},
  
  {"description":"Water Bill",                  "amount":"87.55", "type":"expenses","repetition":"recurring","date":"2020-07-15"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2020-07-23"},
  {"description":"Car fix","amount":"172.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-07-23"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2020-07-23"},
  {"description":"Electricity",      "amount":"212.55","type":"expenses","repetition":"recurring","date":"2020-07-10"},
  {"description":"Clothes","amount":"221.99","type":"expenses","repetition":"nonRecurring",  "date":"2020-07-26"},
  {"description":"Cinema",                "amount":"50.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-07-23"},
  {"description":"Pizza",                 "amount":"33.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-07-19"},
  {"description":"Hamburger",                "amount":"21.70", "type":"expenses","repetition":"nonRecurring",  "date":"2020-07-23"},
  {"description":"ReactJS Book",     "amount":"44.95", "type":"expenses","repetition":"nonRecurring",  "date":"2020-07-13"},
  {"description":"Month Food",        "amount":"454.78","type":"expenses","repetition":"recurring","date":"2020-07-23"},
  
  {"description":"TV",                "amount":"1099.70", "type":"expenses","repetition":"nonRecurring",  "date":"2020-08-23"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2020-08-23"},
  {"description":"Cinema",                "amount":"80.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-08-23"},
  {"description":"Electricity",      "amount":"112.55","type":"expenses","repetition":"recurring","date":"2020-08-10"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2020-08-23"},
  {"description":"Water Bill",                  "amount":"43.55", "type":"expenses","repetition":"recurring","date":"2020-08-15"},
  {"description":"Clothes","amount":"130.99","type":"expenses","repetition":"nonRecurring",  "date":"2020-08-26"},
  {"description":"Pizza",                 "amount":"40.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-08-19"},
  {"description":"ReactJS Book",     "amount":"45.95", "type":"expenses","repetition":"nonRecurring",  "date":"2020-08-13"},
  {"description":"Month Food",        "amount":"525.78","type":"expenses","repetition":"recurring","date":"2020-08-23"},
  {"description":"Car fix","amount":"20.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-08-23"},
  {"description":"Hamburger",                "amount":"35.70", "type":"expenses","repetition":"nonRecurring",  "date":"2020-08-23"},
  
  {"description":"Headset","amount":"399.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-09-23"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2020-09-23"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2020-09-23"},
  {"description":"Pizza",                 "amount":"120.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-09-19"},
  {"description":"Water Bill",                  "amount":"53.55", "type":"expenses","repetition":"recurring","date":"2020-09-15"},
  {"description":"ReactJS Book",     "amount":"32.95", "type":"expenses","repetition":"nonRecurring",  "date":"2020-09-13"},
  {"description":"Clothes","amount":"111.99","type":"expenses","repetition":"nonRecurring",  "date":"2020-09-26"},
  {"description":"Cinema",                "amount":"70.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-09-23"},
  {"description":"Hamburger",                "amount":"55.70", "type":"expenses","repetition":"nonRecurring",  "date":"2020-09-23"},
  {"description":"Month Food",        "amount":"476.78","type":"expenses","repetition":"recurring","date":"2020-09-23"},
  {"description":"Electricity",      "amount":"212.55","type":"expenses","repetition":"recurring","date":"2020-09-10"},
  
  {"description":"Car fix","amount":"110.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-10-23"},
  {"description":"Pizza",                 "amount":"90.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-10-19"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2020-10-23"},
  {"description":"Electricity",      "amount":"192.55","type":"expenses","repetition":"recurring","date":"2020-10-10"},
  {"description":"Month Food",        "amount":"683.78","type":"expenses","repetition":"recurring","date":"2020-10-23"},
  {"description":"Clothes","amount":"230.99","type":"expenses","repetition":"nonRecurring",  "date":"2020-10-26"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2020-10-23"},
  {"description":"Cinema",                "amount":"43.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-10-23"},
  {"description":"Water Bill",                  "amount":"63.55", "type":"expenses","repetition":"recurring","date":"2020-10-15"},
  {"description":"Hamburger",                "amount":"88.70", "type":"expenses","repetition":"nonRecurring",  "date":"2020-10-23"},
  {"description":"ReactJS Book",     "amount":"21.95", "type":"expenses","repetition":"nonRecurring",  "date":"2020-10-13"},
  
  {"description":"Keyboard","amount":"220.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-11-23"},
  {"description":"ReactJS Book",     "amount":"25.95", "type":"expenses","repetition":"nonRecurring",  "date":"2020-11-13"},
  {"description":"Pizza",                 "amount":"30.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-11-19"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2020-11-23"},
  {"description":"Month Food",        "amount":"625.78","type":"expenses","repetition":"recurring","date":"2020-11-23"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2020-11-23"},
  {"description":"Clothes","amount":"212.99","type":"expenses","repetition":"nonRecurring",  "date":"2020-11-26"},
  {"description":"Cinema",                "amount":"20.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-11-23"},
  {"description":"Hamburger",                "amount":"55.70", "type":"expenses","repetition":"nonRecurring",  "date":"2020-11-23"},
  {"description":"Water Bill",                  "amount":"83.55", "type":"expenses","repetition":"recurring","date":"2020-11-15"},
  {"description":"Electricity",      "amount":"182.55","type":"expenses","repetition":"recurring","date":"2020-11-10"},
  
  {"description":"Monitor","amount":"349.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-12-23"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2020-12-23"},
  {"description":"Electricity",      "amount":"231.55","type":"expenses","repetition":"recurring","date":"2020-12-10"},
  {"description":"Water Bill",                  "amount":"67.55", "type":"expenses","repetition":"recurring","date":"2020-12-15"},
  {"description":"ReactJS Book",     "amount":"42.95", "type":"expenses","repetition":"nonRecurring",  "date":"2020-12-13"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2020-12-23"},
  {"description":"Clothes","amount":"111.80","type":"expenses","repetition":"nonRecurring",  "date":"2020-12-26"},
  {"description":"Pizza",                 "amount":"67.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-12-19"},
  {"description":"Month Food",        "amount":"755.78","type":"expenses","repetition":"recurring","date":"2020-12-23"},
  {"description":"Hamburger",                "amount":"55.70", "type":"expenses","repetition":"nonRecurring",  "date":"2020-12-23"},
  {"description":"Cinema",                "amount":"62.00", "type":"expenses","repetition":"nonRecurring",  "date":"2020-12-23"},

  {"description":"Guitar","amount":"899.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-01-23"},
  {"description":"Hamburger",                "amount":"55.70", "type":"expenses","repetition":"nonRecurring",  "date":"2021-01-23"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2021-01-23"},
  {"description":"Water Bill",                  "amount":"63.55", "type":"expenses","repetition":"recurring","date":"2021-01-15"},
  {"description":"Electricity",      "amount":"121.55","type":"expenses","repetition":"recurring","date":"2021-01-10"},
  {"description":"Pizza",                 "amount":"70.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-01-19"},
  {"description":"Month Food",        "amount":"725.78","type":"expenses","repetition":"recurring","date":"2021-01-23"},
  {"description":"Clothes","amount":"122.99","type":"expenses","repetition":"nonRecurring",  "date":"2021-01-26"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2021-01-23"},
  {"description":"ReactJS Book",     "amount":"21.95", "type":"expenses","repetition":"nonRecurring",  "date":"2021-01-13"},
  {"description":"Cinema",                "amount":"110.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-01-23"},

  {"description":"Cinema",                "amount":"25.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-02-23"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2021-02-23"},
  {"description":"Pizza",                 "amount":"88.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-02-19"},
  {"description":"Car fix","amount":"211.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-02-23"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2021-02-23"},
  {"description":"Electricity",      "amount":"162.55","type":"expenses","repetition":"recurring","date":"2021-02-10"},
  {"description":"Books",     "amount":"85.95", "type":"expenses","repetition":"nonRecurring",  "date":"2021-02-13"},
  {"description":"Clothes","amount":"186.99","type":"expenses","repetition":"nonRecurring",  "date":"2021-02-26"},
  {"description":"Month Food",        "amount":"425.78","type":"expenses","repetition":"recurring","date":"2021-02-23"},
  {"description":"Water Bill",                  "amount":"63.55", "type":"expenses","repetition":"recurring","date":"2021-02-15"},
  {"description":"Hamburger",                "amount":"25.70", "type":"expenses","repetition":"nonRecurring",  "date":"2021-02-23"},

  {"description":"Sofa","amount":"1111.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-03-23"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2021-03-23"},
  {"description":"Pizza",                 "amount":"60.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-03-19"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2021-03-23"},
  {"description":"Electricity",      "amount":"123.55","type":"expenses","repetition":"recurring","date":"2021-03-10"},
  {"description":"Clothes","amount":"146.99","type":"expenses","repetition":"nonRecurring",  "date":"2021-03-26"},
  {"description":"Hamburger",                "amount":"28.70", "type":"expenses","repetition":"nonRecurring",  "date":"2021-03-23"},
  {"description":"ReactJS Book",     "amount":"21.95", "type":"expenses","repetition":"nonRecurring",  "date":"2021-03-13"},
  {"description":"Cinema",                "amount":"50.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-03-23"},
  {"description":"Month Food",        "amount":"475.78","type":"expenses","repetition":"recurring","date":"2021-03-23"},
  {"description":"Water Bill",                  "amount":"63.55", "type":"expenses","repetition":"recurring","date":"2021-03-15"},

  {"description":"Piano","amount":"1220.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-04-23"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2021-04-23"},
  {"description":"Electricity",      "amount":"164.55","type":"expenses","repetition":"recurring","date":"2021-04-10"},
  {"description":"Pizza",                 "amount":"55.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-04-19"},
  {"description":"Clothes","amount":"112.99","type":"expenses","repetition":"nonRecurring",  "date":"2021-04-26"},
  {"description":"Water Bill",                  "amount":"72.55", "type":"expenses","repetition":"recurring","date":"2021-04-15"},
  {"description":"Month Food",        "amount":"623.78","type":"expenses","repetition":"recurring","date":"2021-04-23"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2021-04-23"},
  {"description":"ReactJS Book",     "amount":"41.95", "type":"expenses","repetition":"nonRecurring",  "date":"2021-04-13"},
  {"description":"Hamburger",                "amount":"55.70", "type":"expenses","repetition":"nonRecurring",  "date":"2021-04-23"},
  {"description":"Cinema",                "amount":"25.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-04-23"},

  {"description":"Party","amount":"1432.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-05-23"},
  {"description":"Electricity",      "amount":"135.55","type":"expenses","repetition":"recurring","date":"2021-05-10"},
  {"description":"Pizza",                 "amount":"55.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-05-19"},
  {"description":"Water Bill",                  "amount":"73.55", "type":"expenses","repetition":"recurring","date":"2021-05-15"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2021-05-23"},
  {"description":"ReactJS Book",     "amount":"23.95", "type":"expenses","repetition":"nonRecurring",  "date":"2021-05-13"},
  {"description":"Clothes","amount":"188.99","type":"expenses","repetition":"nonRecurring",  "date":"2021-05-26"},
  {"description":"Month Food",        "amount":"475.78","type":"expenses","repetition":"recurring","date":"2021-05-23"},
  {"description":"Hamburger",                "amount":"59.70", "type":"expenses","repetition":"nonRecurring",  "date":"2021-05-23"},
  {"description":"Cinema",                "amount":"42.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-05-23"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2021-05-23"},

  {"description":"Electricity",      "amount":"196.55","type":"expenses","repetition":"recurring","date":"2021-06-10"},
  {"description":"Car fix","amount":"254.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-06-23"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2021-06-23"},
  {"description":"Water Bill",                  "amount":"77.55", "type":"expenses","repetition":"recurring","date":"2021-06-15"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2021-06-23"},
  {"description":"Pizza",                 "amount":"40.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-06-19"},
  {"description":"Cinema",                "amount":"65.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-06-23"},
  {"description":"Month Food",        "amount":"465.78","type":"expenses","repetition":"recurring","date":"2021-06-23"},
  {"description":"Hamburger",                "amount":"25.70", "type":"expenses","repetition":"nonRecurring",  "date":"2021-06-23"},
  {"description":"Books",     "amount":"96.95", "type":"expenses","repetition":"nonRecurring",  "date":"2021-06-13"},
  {"description":"Clothes","amount":"352.99","type":"expenses","repetition":"nonRecurring",  "date":"2021-06-26"},

  {"description":"Jewel","amount":"999.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-07-23"},
  {"description":"Electricity",      "amount":"197.55","type":"expenses","repetition":"recurring","date":"2021-07-10"},
  {"description":"Pizza",                 "amount":"69.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-07-19"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2021-07-23"},
  {"description":"Clothes","amount":"123.99","type":"expenses","repetition":"nonRecurring",  "date":"2021-07-26"},
  {"description":"Cinema",                "amount":"54.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-07-23"},
  {"description":"Month Food",        "amount":"448.78","type":"expenses","repetition":"recurring","date":"2021-07-23"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2021-07-23"},
  {"description":"ReactJS Book",     "amount":"32.95", "type":"expenses","repetition":"nonRecurring",  "date":"2021-07-13"},
  {"description":"Hamburger",                "amount":"51.70", "type":"expenses","repetition":"nonRecurring",  "date":"2021-07-23"},
  {"description":"Water Bill",                  "amount":"62.55", "type":"expenses","repetition":"recurring","date":"2021-07-15"},

  {"description":"Pizza",                 "amount":"85.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-08-19"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2021-08-23"},
  {"description":"Electricity",      "amount":"198.55","type":"expenses","repetition":"recurring","date":"2021-08-10"},
  {"description":"Car fix","amount":"311.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-08-23"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2021-08-23"},
  {"description":"Clothes","amount":"122.99","type":"expenses","repetition":"nonRecurring",  "date":"2021-08-26"},
  {"description":"Cinema",                "amount":"46.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-08-23"},
  {"description":"Month Food",        "amount":"486.78","type":"expenses","repetition":"recurring","date":"2021-08-23"},
  {"description":"ReactJS Book",     "amount":"22.95", "type":"expenses","repetition":"nonRecurring",  "date":"2021-08-13"},
  {"description":"Hamburger",                "amount":"45.70", "type":"expenses","repetition":"nonRecurring",  "date":"2021-08-23"},
  {"description":"Water Bill",                  "amount":"73.55", "type":"expenses","repetition":"recurring","date":"2021-08-15"},

  {"description":"Notebook","amount":"1899.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-09-23"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2021-09-23"},
  {"description":"Pizza",                 "amount":"56.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-09-19"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2021-09-23"},
  {"description":"Month Food",        "amount":"487.78","type":"expenses","repetition":"recurring","date":"2021-09-23"},
  {"description":"Clothes","amount":"148.99","type":"expenses","repetition":"nonRecurring",  "date":"2021-09-26"},
  {"description":"ReactJS Book",     "amount":"56.95", "type":"expenses","repetition":"nonRecurring",  "date":"2021-09-13"},
  {"description":"Hamburger",                "amount":"41.70", "type":"expenses","repetition":"nonRecurring",  "date":"2021-09-23"},
  {"description":"Water Bill",                  "amount":"63.55", "type":"expenses","repetition":"recurring","date":"2021-09-15"},
  {"description":"Electricity",      "amount":"199.55","type":"expenses","repetition":"recurring","date":"2021-09-10"},
  {"description":"Cinema",                "amount":"36.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-09-23"},

  {"description":"Month Food",        "amount":"429.78","type":"expenses","repetition":"recurring","date":"2021-10-23"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2021-10-23"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2021-10-23"},
  {"description":"Books",     "amount":"65.95", "type":"expenses","repetition":"nonRecurring",  "date":"2021-10-13"},
  {"description":"Car fix","amount":"154.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-10-23"},
  {"description":"Pizza",                 "amount":"40.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-10-19"},
  {"description":"Water Bill",                  "amount":"63.55", "type":"expenses","repetition":"recurring","date":"2021-10-15"},
  {"description":"Clothes","amount":"254.99","type":"expenses","repetition":"nonRecurring",  "date":"2021-10-26"},
  {"description":"Electricity",      "amount":"215.55","type":"expenses","repetition":"recurring","date":"2021-10-10"},
  {"description":"Cinema",                "amount":"98.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-10-23"},
  {"description":"Hamburger",                "amount":"63.70", "type":"expenses","repetition":"nonRecurring",  "date":"2021-10-23"},

  {"description":"Cellphone","amount":"1099.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-11-23"},
  {"description":"Books",     "amount":"49.95", "type":"expenses","repetition":"nonRecurring",  "date":"2021-11-13"},
  {"description":"Pizza",                 "amount":"45.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-11-19"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2021-11-23"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2021-11-23"},
  {"description":"Clothes","amount":"152.99","type":"expenses","repetition":"nonRecurring",  "date":"2021-11-26"},
  {"description":"Water Bill",                  "amount":"77.55", "type":"expenses","repetition":"recurring","date":"2021-11-15"},
  {"description":"Month Food",        "amount":"577.78","type":"expenses","repetition":"recurring","date":"2021-11-23"},
  {"description":"Electricity",      "amount":"211.55","type":"expenses","repetition":"recurring","date":"2021-11-10"},
  {"description":"Cinema",                "amount":"65.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-11-23"},
  {"description":"Hamburger",                "amount":"74.70", "type":"expenses","repetition":"nonRecurring",  "date":"2021-11-23"},

  {"description":"Trip","amount":"1287.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-12-23"},
  {"description":"Electricity",      "amount":"231.55","type":"expenses","repetition":"recurring","date":"2021-12-10"},
  {"description":"Cinema",                "amount":"63.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-12-23"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2021-12-23"},
  {"description":"Pizza",                 "amount":"40.00", "type":"expenses","repetition":"nonRecurring",  "date":"2021-12-19"},
  {"description":"Water Bill",                  "amount":"73.55", "type":"expenses","repetition":"recurring","date":"2021-12-15"},
  {"description":"Month Food",        "amount":"488.78","type":"expenses","repetition":"recurring","date":"2021-12-23"},
  {"description":"Clothes","amount":"162.99","type":"expenses","repetition":"nonRecurring",  "date":"2021-12-26"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2021-12-23"},
  {"description":"Hamburger",                "amount":"29.70", "type":"expenses","repetition":"nonRecurring",  "date":"2021-12-23"},
  {"description":"ReactJS Book",     "amount":"41.95", "type":"expenses","repetition":"nonRecurring",  "date":"2021-12-13"},

  {"description":"Shoes","amount":"220.00", "type":"expenses","repetition":"nonRecurring",  "date":"2022-01-23"},
  {"description":"Clothes","amount":"213.99","type":"expenses","repetition":"nonRecurring",  "date":"2022-01-26"},
  {"description":"Electricity",      "amount":"161.55","type":"expenses","repetition":"recurring","date":"2022-01-10"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2022-01-23"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2022-01-23"},
  {"description":"Water Bill",                  "amount":"63.55", "type":"expenses","repetition":"recurring","date":"2022-01-15"},
  {"description":"Pizza",                 "amount":"81.00", "type":"expenses","repetition":"nonRecurring",  "date":"2022-01-19"},
  {"description":"Cinema",                "amount":"63.00", "type":"expenses","repetition":"nonRecurring",  "date":"2022-01-23"},
  {"description":"Hamburger",                "amount":"29.70", "type":"expenses","repetition":"nonRecurring",  "date":"2022-01-23"},
  {"description":"Month Food",        "amount":"511.78","type":"expenses","repetition":"recurring","date":"2022-01-23"},
  {"description":"ReactJS Book",     "amount":"48.95", "type":"expenses","repetition":"nonRecurring",  "date":"2022-01-13"},

  {"description":"Watch","amount":"999.00", "type":"expenses","repetition":"nonRecurring",  "date":"2022-02-23"},
  {"description":"Month Food",        "amount":"455.78","type":"expenses","repetition":"recurring","date":"2022-02-23"},
  {"description":"Electricity",      "amount":"252.55","type":"expenses","repetition":"recurring","date":"2022-02-10"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2022-02-23"},
  {"description":"Water Bill",                  "amount":"46.55", "type":"expenses","repetition":"recurring","date":"2022-02-15"},
  {"description":"Pizza",                 "amount":"20.00", "type":"expenses","repetition":"nonRecurring",  "date":"2022-02-19"},
  {"description":"Clothes","amount":"148.99","type":"expenses","repetition":"nonRecurring",  "date":"2022-02-26"},
  {"description":"Cinema",                "amount":"20.00", "type":"expenses","repetition":"nonRecurring",  "date":"2022-02-23"},
  {"description":"Books",     "amount":"60.95", "type":"expenses","repetition":"nonRecurring",  "date":"2022-02-13"},
  {"description":"Hamburger",                "amount":"29.70", "type":"expenses","repetition":"nonRecurring",  "date":"2022-02-23"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2022-02-23"},

  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2022-03-23"},
  {"description":"Electricity",      "amount":"143.55","type":"expenses","repetition":"recurring","date":"2022-03-10"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2022-03-23"},
  {"description":"Pizza",                 "amount":"25.00", "type":"expenses","repetition":"nonRecurring",  "date":"2022-03-19"},
  {"description":"Courses","amount":"999.00", "type":"expenses","repetition":"nonRecurring",  "date":"2022-03-23"},
  {"description":"Clothes","amount":"90.99","type":"expenses","repetition":"nonRecurring",  "date":"2022-03-26"},
  {"description":"Hamburger",                "amount":"42.70", "type":"expenses","repetition":"nonRecurring",  "date":"2022-03-23"},
  {"description":"Cinema",                "amount":"25.00", "type":"expenses","repetition":"nonRecurring",  "date":"2022-03-23"},
  {"description":"Month Food",        "amount":"421.78","type":"expenses","repetition":"recurring","date":"2022-03-23"},
  {"description":"Water Bill",                  "amount":"49.55", "type":"expenses","repetition":"recurring","date":"2022-03-15"},
  {"description":"ReactJS Book",     "amount":"33.95", "type":"expenses","repetition":"nonRecurring",  "date":"2022-03-13"},

  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2022-04-23"},
  {"description":"Electricity",      "amount":"124.55","type":"expenses","repetition":"recurring","date":"2022-04-10"},
  {"description":"Pizza",                 "amount":"42.00", "type":"expenses","repetition":"nonRecurring",  "date":"2022-04-19"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2022-04-23"},
  {"description":"Car fix","amount":"232.00", "type":"expenses","repetition":"nonRecurring",  "date":"2022-04-23"},
  {"description":"Hamburger",                "amount":"25.70", "type":"expenses","repetition":"nonRecurring",  "date":"2022-04-23"},
  {"description":"Water Bill",                  "amount":"63.55", "type":"expenses","repetition":"recurring","date":"2022-04-15"},
  {"description":"Month Food",        "amount":"565.78","type":"expenses","repetition":"recurring","date":"2022-04-23"},
  {"description":"Cinema",                "amount":"60.00", "type":"expenses","repetition":"nonRecurring",  "date":"2022-04-23"},
  {"description":"ReactJS Book",     "amount":"46.95", "type":"expenses","repetition":"nonRecurring",  "date":"2022-04-13"},
  {"description":"Clothes","amount":"160.99","type":"expenses","repetition":"nonRecurring",  "date":"2022-04-26"},

  {"description":"Bike","amount":"1599.00", "type":"expenses","repetition":"nonRecurring",  "date":"2022-05-23"},
  {"description":"Pizza",                 "amount":"90.00", "type":"expenses","repetition":"nonRecurring",  "date":"2022-05-19"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2022-05-23"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2022-05-23"},
  {"description":"Clothes","amount":"230.99","type":"expenses","repetition":"nonRecurring",  "date":"2022-05-26"},
  {"description":"Water Bill",                  "amount":"93.55", "type":"expenses","repetition":"recurring","date":"2022-05-15"},
  {"description":"Electricity",      "amount":"255.55","type":"expenses","repetition":"recurring","date":"2022-05-10"},
  {"description":"Month Food",        "amount":"525.78","type":"expenses","repetition":"recurring","date":"2022-05-23"},
  {"description":"Cinema",                "amount":"80.00", "type":"expenses","repetition":"nonRecurring",  "date":"2022-05-23"},
  {"description":"Hamburger",                "amount":"35.70", "type":"expenses","repetition":"nonRecurring",  "date":"2022-05-23"},
  {"description":"ReactJS Book",     "amount":"45.95", "type":"expenses","repetition":"nonRecurring",  "date":"2022-05-13"},

  {"description":"Hamburger",                "amount":"45.70", "type":"expenses","repetition":"nonRecurring",  "date":"2022-06-23"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2022-06-23"},
  {"description":"Cinema",                "amount":"80.00", "type":"expenses","repetition":"nonRecurring",  "date":"2022-06-23"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2022-06-23"},
  {"description":"Pizza",                 "amount":"140.00", "type":"expenses","repetition":"nonRecurring",  "date":"2022-06-19"},
  {"description":"Water Bill",                  "amount":"83.55", "type":"expenses","repetition":"recurring","date":"2022-06-15"},
  {"description":"Clothes","amount":"150.99","type":"expenses","repetition":"nonRecurring",  "date":"2022-06-26"},
  {"description":"Month Food",        "amount":"625.78","type":"expenses","repetition":"recurring","date":"2022-06-23"},
  {"description":"ReactJS Book",     "amount":"55.95", "type":"expenses","repetition":"nonRecurring",  "date":"2022-06-13"},
  {"description":"Electricity",      "amount":"156.55","type":"expenses","repetition":"recurring","date":"2022-06-10"},
  {"description":"Car fix","amount":"310.00", "type":"expenses","repetition":"nonRecurring",  "date":"2022-06-23"},

  {"description":"Bed","amount":"1099.00", "type":"expenses","repetition":"nonRecurring",  "date":"2022-07-23"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2022-07-23"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2022-07-23"},
  {"description":"Pizza",                 "amount":"50.00", "type":"expenses","repetition":"nonRecurring",  "date":"2022-07-19"},
  {"description":"Water Bill",                  "amount":"73.55", "type":"expenses","repetition":"recurring","date":"2022-07-15"},
  {"description":"Clothes","amount":"180.99","type":"expenses","repetition":"nonRecurring",  "date":"2022-07-26"},
  {"description":"Hamburger",                "amount":"45.70", "type":"expenses","repetition":"nonRecurring",  "date":"2022-07-23"},
  {"description":"Month Food",        "amount":"545.78","type":"expenses","repetition":"recurring","date":"2022-07-23"},
  {"description":"Electricity",      "amount":"147.55","type":"expenses","repetition":"recurring","date":"2022-07-10"},
  {"description":"Cinema",                "amount":"65.00", "type":"expenses","repetition":"nonRecurring",  "date":"2022-07-23"},
  {"description":"ReactJS Book",     "amount":"22.95", "type":"expenses","repetition":"nonRecurring",  "date":"2022-07-13"},

  {"description":"Courses","amount":"920.00", "type":"expenses","repetition":"nonRecurring",  "date":"2022-08-23"},
  {"description":"ReactJS Book",     "amount":"39.95", "type":"expenses","repetition":"nonRecurring",  "date":"2022-08-13"},
  {"description": "Phone Bill",             "amount":"99.99", "type":"expenses","repetition":"recurring","date":"2022-08-23"},
  {"description":"Pizza",                 "amount":"45.00", "type":"expenses","repetition":"nonRecurring",  "date":"2022-08-19"},
  {"description":"Month Food",        "amount":"725.78","type":"expenses","repetition":"recurring","date":"2022-08-23"},
  {"description":"Water Bill",                  "amount":"63.55", "type":"expenses","repetition":"recurring","date":"2022-08-15"},
  {"description":"Clothes","amount":"110.99","type":"expenses","repetition":"nonRecurring",  "date":"2022-08-26"},
  {"description":"Electricity",      "amount":"128.55","type":"expenses","repetition":"recurring","date":"2022-08-10"},
  {"description":"Cinema",                "amount":"60.00", "type":"expenses","repetition":"nonRecurring",  "date":"2022-08-23"},
  {"description":"Health Insurance Bill",        "amount":"300.00","type":"expenses","repetition":"recurring","date":"2022-08-23"},
  {"description":"Hamburger",                "amount":"44.70", "type":"expenses","repetition":"nonRecurring",  "date":"2022-08-23"},
]

export default expenses