const income = [
  { "description": "Salary",     "amount": "1400.52", "type": "income", "repetition": "recurring", "date": "2020-01-10" }, 
  { "description": "Freelancer Job",      "amount": "148.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-01-17" },
  { "description": "iOS Apps Income",      "amount": "37.13",  "type": "income", "repetition": "recurring",   "date": "2020-01-22" },
  { "description": "Cloth Selling",      "amount": "75.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-01-22" },
  { "description": "Freelancer Job",      "amount": "220.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-01-22" },
  { "description": "Course Selling",     "amount": "110.23", "type": "income", "repetition": "nonRecurring", "date": "2020-01-10" },
  { "description": "Android Apps Income",     "amount": "49.23", "type": "income", "repetition": "recurring", "date": "2020-01-10" },
  { "description": "Investiments",     "amount": "88.23", "type": "income", "repetition": "recurring", "date": "2020-01-10" },
  { "description": "Freelancer Site", "amount": "200.23",  "type": "income", "repetition": "nonRecurring",   "date": "2020-01-21" },
  
  { "description": "Freelancer Job",      "amount": "348.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-02-17" },
  { "description": "Freelancer Job",      "amount": "220.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-02-22" },
  { "description": "Salary",     "amount": "1400.52", "type": "income", "repetition": "recurring", "date": "2020-02-10" }, 
  { "description": "Android Apps Income",     "amount": "149.23", "type": "income", "repetition": "recurring", "date": "2020-02-10" },
  { "description": "iOS Apps Income",      "amount": "227.13",  "type": "income", "repetition": "recurring",   "date": "2020-02-22" },
  { "description": "Cloth Selling",      "amount": "25.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-02-22" },
  { "description": "Investiments",     "amount": "88.23", "type": "income", "repetition": "recurring", "date": "2020-02-10" },
  { "description": "Freelancer Site", "amount": "180.23",  "type": "income", "repetition": "nonRecurring",   "date": "2020-02-21" },
  { "description": "Course Selling",     "amount": "210.23", "type": "income", "repetition": "nonRecurring", "date": "2020-02-10" },

  { "description": "Freelancer Job",      "amount": "48.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-03-17" },
  { "description": "Freelancer Site", "amount": "180.23",  "type": "income", "repetition": "nonRecurring",   "date": "2020-03-21" },
  { "description": "Freelancer Job",      "amount": "170.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-03-22" },
  { "description": "Salary",     "amount": "1400.52", "type": "income", "repetition": "recurring", "date": "2020-03-10" }, 
  { "description": "Cloth Selling",      "amount": "35.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-03-22" },
  { "description": "Android Apps Income",     "amount": "49.23", "type": "income", "repetition": "recurring", "date": "2020-03-10" },
  { "description": "Investiments",     "amount": "88.23", "type": "income", "repetition": "recurring", "date": "2020-03-10" },
  { "description": "Course Selling",     "amount": "100.23", "type": "income", "repetition": "nonRecurring", "date": "2020-03-10" },
  { "description": "iOS Apps Income",      "amount": "37.13",  "type": "income", "repetition": "recurring",   "date": "2020-03-22" },

  { "description": "Salary",     "amount": "1400.52", "type": "income", "repetition": "recurring", "date": "2020-04-10" }, 
  { "description": "Freelancer Job",      "amount": "320.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-04-22" },
  { "description": "Freelancer Job",      "amount": "248.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-04-17" },
  { "description": "Cloth Selling",      "amount": "70.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-04-22" },
  { "description": "Freelancer Site", "amount": "220.23",  "type": "income", "repetition": "nonRecurring",   "date": "2020-04-21" },
  { "description": "Android Apps Income",     "amount": "249.23", "type": "income", "repetition": "recurring", "date": "2020-04-10" },
  { "description": "iOS Apps Income",      "amount": "150.13",  "type": "income", "repetition": "recurring",   "date": "2020-04-22" },
  { "description": "Investiments",     "amount": "158.23", "type": "income", "repetition": "recurring", "date": "2020-04-10" },
  { "description": "Course Selling",     "amount": "190.23", "type": "income", "repetition": "nonRecurring", "date": "2020-04-10" },

  { "description": "Freelancer Job",      "amount": "148.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-05-17" },
  { "description": "Salary",     "amount": "1400.52", "type": "income", "repetition": "recurring", "date": "2020-05-10" }, 
  { "description": "Android Apps Income",     "amount": "49.23", "type": "income", "repetition": "recurring", "date": "2020-05-10" },
  { "description": "Freelancer Job",      "amount": "220.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-05-22" },
  { "description": "Cloth Selling",      "amount": "75.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-05-22" },
  { "description": "Course Selling",     "amount": "110.23", "type": "income", "repetition": "nonRecurring", "date": "2020-05-10" },
  { "description": "iOS Apps Income",      "amount": "37.13",  "type": "income", "repetition": "recurring",   "date": "2020-05-22" },
  { "description": "Freelancer Site", "amount": "200.23",  "type": "income", "repetition": "nonRecurring",   "date": "2020-05-21" },
  { "description": "Investiments",     "amount": "88.23", "type": "income", "repetition": "recurring", "date": "2020-05-10" },

  { "description": "Salary",     "amount": "1500.52", "type": "income", "repetition": "recurring", "date": "2020-06-10" }, 
  { "description": "Cloth Selling",      "amount": "55.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-06-22" },
  { "description": "Freelancer Job",      "amount": "200.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-06-22" },
  { "description": "iOS Apps Income",      "amount": "65.13",  "type": "income", "repetition": "recurring",   "date": "2020-06-22" },
  { "description": "Freelancer Job",      "amount": "128.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-06-17" },
  { "description": "Course Selling",     "amount": "120.23", "type": "income", "repetition": "nonRecurring", "date": "2020-06-10" },
  { "description": "Freelancer Site", "amount": "224.23",  "type": "income", "repetition": "nonRecurring",   "date": "2020-06-21" },
  { "description": "Investiments",     "amount": "122.23", "type": "income", "repetition": "recurring", "date": "2020-06-10" },
  { "description": "Android Apps Income",     "amount": "54.23", "type": "income", "repetition": "recurring", "date": "2020-06-10" },

  { "description": "Freelancer Job",      "amount": "348.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-07-17" },
  { "description": "Salary",     "amount": "1500.52", "type": "income", "repetition": "recurring", "date": "2020-07-10" }, 
  { "description": "Cloth Selling",      "amount": "45.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-07-22" },
  { "description": "iOS Apps Income",      "amount": "237.13",  "type": "income", "repetition": "recurring",   "date": "2020-07-22" },
  { "description": "Freelancer Job",      "amount": "260.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-07-22" },
  { "description": "Freelancer Site", "amount": "230.23",  "type": "income", "repetition": "nonRecurring",   "date": "2020-07-21" },
  { "description": "Course Selling",     "amount": "210.23", "type": "income", "repetition": "nonRecurring", "date": "2020-07-10" },
  { "description": "Investiments",     "amount": "158.23", "type": "income", "repetition": "recurring", "date": "2020-07-10" },
  { "description": "Android Apps Income",     "amount": "449.23", "type": "income", "repetition": "recurring", "date": "2020-07-10" },

  { "description": "Freelancer Job",      "amount": "258.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-08-17" },
  { "description": "Android Apps Income",     "amount": "149.23", "type": "income", "repetition": "recurring", "date": "2020-08-10" },
  { "description": "Freelancer Job",      "amount": "340.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-08-22" },
  { "description": "Salary",     "amount": "1500.52", "type": "income", "repetition": "recurring", "date": "2020-08-10" }, 
  { "description": "Cloth Selling",      "amount": "33.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-08-22" },
  { "description": "Freelancer Site", "amount": "210.23",  "type": "income", "repetition": "nonRecurring",   "date": "2020-08-21" },
  { "description": "Course Selling",     "amount": "230.23", "type": "income", "repetition": "nonRecurring", "date": "2020-08-10" },
  { "description": "Investiments",     "amount": "48.23", "type": "income", "repetition": "recurring", "date": "2020-08-10" },
  { "description": "iOS Apps Income",      "amount": "125.13",  "type": "income", "repetition": "recurring",   "date": "2020-08-22" },

  { "description": "Freelancer Job",      "amount": "225.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-09-17" },
  { "description": "Salary",     "amount": "1500.52", "type": "income", "repetition": "recurring", "date": "2020-09-10" }, 
  { "description": "iOS Apps Income",      "amount": "27.13",  "type": "income", "repetition": "recurring",   "date": "2020-09-22" },
  { "description": "Cloth Selling",      "amount": "155.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-09-22" },
  { "description": "Course Selling",     "amount": "130.23", "type": "income", "repetition": "nonRecurring", "date": "2020-09-10" },
  { "description": "Android Apps Income",     "amount": "29.23", "type": "income", "repetition": "recurring", "date": "2020-09-10" },
  { "description": "Investiments",     "amount": "321.23", "type": "income", "repetition": "recurring", "date": "2020-09-10" },
  { "description": "Freelancer Site", "amount": "540.23",  "type": "income", "repetition": "nonRecurring",   "date": "2020-09-21" },
  { "description": "Freelancer Job",      "amount": "140.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-09-22" },

  { "description": "Freelancer Job",      "amount": "120.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-10-22" },
  { "description": "Android Apps Income",     "amount": "99.23", "type": "income", "repetition": "recurring", "date": "2020-10-10" },
  { "description": "Salary",     "amount": "1500.52", "type": "income", "repetition": "recurring", "date": "2020-10-10" }, 
  { "description": "Cloth Selling",      "amount": "45.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-10-22" },
  { "description": "Freelancer Job",      "amount": "128.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-10-17" },
  { "description": "Freelancer Site", "amount": "130.23",  "type": "income", "repetition": "nonRecurring",   "date": "2020-10-21" },
  { "description": "Course Selling",     "amount": "210.23", "type": "income", "repetition": "nonRecurring", "date": "2020-10-10" },
  { "description": "iOS Apps Income",      "amount": "88.13",  "type": "income", "repetition": "recurring",   "date": "2020-10-22" },
  { "description": "Investiments",     "amount": "148.23", "type": "income", "repetition": "recurring", "date": "2020-10-10" },

  { "description": "Freelancer Job",      "amount": "348.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-11-17" },
  { "description": "iOS Apps Income",      "amount": "237.13",  "type": "income", "repetition": "recurring",   "date": "2020-11-22" },
  { "description": "Cloth Selling",      "amount": "54.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-11-22" },
  { "description": "Freelancer Job",      "amount": "230.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-11-22" },
  { "description": "Investiments",     "amount": "188.23", "type": "income", "repetition": "recurring", "date": "2020-11-10" },
  { "description": "Freelancer Site", "amount": "240.23",  "type": "income", "repetition": "nonRecurring",   "date": "2020-11-21" },
  { "description": "Salary",     "amount": "1500.52", "type": "income", "repetition": "recurring", "date": "2020-11-10" }, 
  { "description": "Course Selling",     "amount": "210.23", "type": "income", "repetition": "nonRecurring", "date": "2020-11-10" },
  { "description": "Android Apps Income",     "amount": "349.23", "type": "income", "repetition": "recurring", "date": "2020-11-10" },

  { "description": "iOS Apps Income",      "amount": "127.13",  "type": "income", "repetition": "recurring",   "date": "2020-12-22" },
  { "description": "Freelancer Job",      "amount": "448.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-12-17" },
  { "description": "Freelancer Job",      "amount": "122.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-12-22" },
  { "description": "Cloth Selling",      "amount": "35.13",  "type": "income", "repetition": "nonRecurring",   "date": "2020-12-22" },
  { "description": "Investiments",     "amount": "58.23", "type": "income", "repetition": "recurring", "date": "2020-12-10" },
  { "description": "Android Apps Income",     "amount": "159.23", "type": "income", "repetition": "recurring", "date": "2020-12-10" },
  { "description": "Freelancer Site", "amount": "110.23",  "type": "income", "repetition": "nonRecurring",   "date": "2020-12-21" },
  { "description": "Course Selling",     "amount": "210.23", "type": "income", "repetition": "nonRecurring", "date": "2020-12-10" },
  { "description": "Salary",     "amount": "1500.52", "type": "income", "repetition": "recurring", "date": "2020-12-10" }, 

  { "description": "iOS Apps Income",      "amount": "297.13",  "type": "income", "repetition": "recurring",   "date": "2021-01-22" },
  { "description": "Freelancer Job",      "amount": "320.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-01-22" },
  { "description": "Cloth Selling",      "amount": "35.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-01-22" },
  { "description": "Freelancer Job",      "amount": "248.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-01-17" },
  { "description": "Course Selling",     "amount": "153.23", "type": "income", "repetition": "nonRecurring", "date": "2021-01-10" },
  { "description": "Salary",     "amount": "1500.52", "type": "income", "repetition": "recurring", "date": "2021-01-10" }, 
  { "description": "Freelancer Site", "amount": "254.23",  "type": "income", "repetition": "nonRecurring",   "date": "2021-01-21" },
  { "description": "Android Apps Income",     "amount": "169.23", "type": "income", "repetition": "recurring", "date": "2021-01-10" },
  { "description": "Investiments",     "amount": "128.23", "type": "income", "repetition": "recurring", "date": "2021-01-10" },

  { "description": "Cloth Selling",      "amount": "22.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-02-22" },
  { "description": "Freelancer Job",      "amount": "120.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-02-22" },
  { "description": "Salary",     "amount": "1570.52", "type": "income", "repetition": "recurring", "date": "2021-02-10" }, 
  { "description": "Course Selling",     "amount": "140.23", "type": "income", "repetition": "nonRecurring", "date": "2021-02-10" },
  { "description": "iOS Apps Income",      "amount": "54.13",  "type": "income", "repetition": "recurring",   "date": "2021-02-22" },
  { "description": "Freelancer Job",      "amount": "88.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-02-17" },
  { "description": "Freelancer Site", "amount": "123.23",  "type": "income", "repetition": "nonRecurring",   "date": "2021-02-21" },
  { "description": "Investiments",     "amount": "233.23", "type": "income", "repetition": "recurring", "date": "2021-02-10" },
  { "description": "Android Apps Income",     "amount": "76.23", "type": "income", "repetition": "recurring", "date": "2021-02-10" },

  { "description": "Freelancer Job",      "amount": "320.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-03-22" },
  { "description": "iOS Apps Income",      "amount": "54.13",  "type": "income", "repetition": "recurring",   "date": "2021-03-22" },
  { "description": "Cloth Selling",      "amount": "25.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-03-22" },
  { "description": "Investiments",     "amount": "122.23", "type": "income", "repetition": "recurring", "date": "2021-03-10" },
  { "description": "Freelancer Job",      "amount": "648.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-03-17" },
  { "description": "Android Apps Income",     "amount": "23.23", "type": "income", "repetition": "recurring", "date": "2021-03-10" },
  { "description": "Salary",     "amount": "1570.52", "type": "income", "repetition": "recurring", "date": "2021-03-10" }, 
  { "description": "Freelancer Site", "amount": "124.23",  "type": "income", "repetition": "nonRecurring",   "date": "2021-03-21" },
  { "description": "Course Selling",     "amount": "340.23", "type": "income", "repetition": "nonRecurring", "date": "2021-03-10" },

  { "description": "Freelancer Job",      "amount": "520.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-04-22" },
  { "description": "Salary",     "amount": "1570.52", "type": "income", "repetition": "recurring", "date": "2021-04-10" }, 
  { "description": "iOS Apps Income",      "amount": "127.13",  "type": "income", "repetition": "recurring",   "date": "2021-04-22" },
  { "description": "Freelancer Job",      "amount": "248.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-04-17" },
  { "description": "Course Selling",     "amount": "178.23", "type": "income", "repetition": "nonRecurring", "date": "2021-04-10" },
  { "description": "Android Apps Income",     "amount": "154.23", "type": "income", "repetition": "recurring", "date": "2021-04-10" },
  { "description": "Freelancer Site", "amount": "187.23",  "type": "income", "repetition": "nonRecurring",   "date": "2021-04-21" },
  { "description": "Cloth Selling",      "amount": "31.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-04-22" },
  { "description": "Investiments",     "amount": "176.23", "type": "income", "repetition": "recurring", "date": "2021-04-10" },

  { "description": "Android Apps Income",     "amount": "143.23", "type": "income", "repetition": "recurring", "date": "2021-05-10" },
  { "description": "Freelancer Job",      "amount": "144.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-05-17" },
  { "description": "Cloth Selling",      "amount": "55.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-05-22" },
  { "description": "iOS Apps Income",      "amount": "126.13",  "type": "income", "repetition": "recurring",   "date": "2021-05-22" },
  { "description": "Freelancer Site", "amount": "178.23",  "type": "income", "repetition": "nonRecurring",   "date": "2021-05-21" },
  { "description": "Freelancer Job",      "amount": "213.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-05-22" },
  { "description": "Investiments",     "amount": "123.23", "type": "income", "repetition": "recurring", "date": "2021-05-10" },
  { "description": "Course Selling",     "amount": "88.23", "type": "income", "repetition": "nonRecurring", "date": "2021-05-10" },
  { "description": "Salary",     "amount": "1570.52", "type": "income", "repetition": "recurring", "date": "2021-05-10" }, 

  { "description": "Cloth Selling",      "amount": "65.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-06-22" },
  { "description": "Freelancer Job",      "amount": "320.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-06-22" },
  { "description": "iOS Apps Income",      "amount": "237.13",  "type": "income", "repetition": "recurring",   "date": "2021-06-22" },
  { "description": "Investiments",     "amount": "121.23", "type": "income", "repetition": "recurring", "date": "2021-06-10" },
  { "description": "Salary",     "amount": "1570.52", "type": "income", "repetition": "recurring", "date": "2021-06-10" }, 
  { "description": "Freelancer Job",      "amount": "748.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-06-17" },
  { "description": "Course Selling",     "amount": "165.23", "type": "income", "repetition": "nonRecurring", "date": "2021-06-10" },
  { "description": "Freelancer Site", "amount": "189.23",  "type": "income", "repetition": "nonRecurring",   "date": "2021-06-21" },
  { "description": "Android Apps Income",     "amount": "249.23", "type": "income", "repetition": "recurring", "date": "2021-06-10" },

  { "description": "Freelancer Job",      "amount": "448.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-07-17" },
  { "description": "Salary",     "amount": "1570.52", "type": "income", "repetition": "recurring", "date": "2021-07-10" }, 
  { "description": "Cloth Selling",      "amount": "46.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-07-22" },
  { "description": "Android Apps Income",     "amount": "176.23", "type": "income", "repetition": "recurring", "date": "2021-07-10" },
  { "description": "Freelancer Site", "amount": "187.23",  "type": "income", "repetition": "nonRecurring",   "date": "2021-07-21" },
  { "description": "Freelancer Job",      "amount": "330.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-07-22" },
  { "description": "Course Selling",     "amount": "130.23", "type": "income", "repetition": "nonRecurring", "date": "2021-07-10" },
  { "description": "Investiments",     "amount": "122.23", "type": "income", "repetition": "recurring", "date": "2021-07-10" },
  { "description": "iOS Apps Income",      "amount": "214.13",  "type": "income", "repetition": "recurring",   "date": "2021-07-22" },

  { "description": "Freelancer Job",      "amount": "348.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-08-17" },
  { "description": "Android Apps Income",     "amount": "182.23", "type": "income", "repetition": "recurring", "date": "2021-08-10" },
  { "description": "Cloth Selling",      "amount": "121.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-08-22" },
  { "description": "Freelancer Job",      "amount": "243.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-08-22" },
  { "description": "iOS Apps Income",      "amount": "176.13",  "type": "income", "repetition": "recurring",   "date": "2021-08-22" },
  { "description": "Freelancer Site", "amount": "198.23",  "type": "income", "repetition": "nonRecurring",   "date": "2021-08-21" },
  { "description": "Salary",     "amount": "1570.52", "type": "income", "repetition": "recurring", "date": "2021-08-10" }, 
  { "description": "Investiments",     "amount": "111.23", "type": "income", "repetition": "recurring", "date": "2021-08-10" },
  { "description": "Course Selling",     "amount": "99.23", "type": "income", "repetition": "nonRecurring", "date": "2021-08-10" },

  { "description": "Freelancer Job",      "amount": "228.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-09-17" },
  { "description": "Cloth Selling",      "amount": "121.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-09-22" },
  { "description": "Freelancer Job",      "amount": "233.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-09-22" },
  { "description": "Salary",     "amount": "1570.52", "type": "income", "repetition": "recurring", "date": "2021-09-10" }, 
  { "description": "Android Apps Income",     "amount": "126.23", "type": "income", "repetition": "recurring", "date": "2021-09-10" },
  { "description": "Freelancer Site", "amount": "276.23",  "type": "income", "repetition": "nonRecurring",   "date": "2021-09-21" },
  { "description": "iOS Apps Income",      "amount": "111.13",  "type": "income", "repetition": "recurring",   "date": "2021-09-22" },
  { "description": "Investiments",     "amount": "172.23", "type": "income", "repetition": "recurring", "date": "2021-09-10" },
  { "description": "Course Selling",     "amount": "155.23", "type": "income", "repetition": "nonRecurring", "date": "2021-09-10" },

  { "description": "Freelancer Job",      "amount": "317.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-10-22" },
  { "description": "Salary",     "amount": "1720.52", "type": "income", "repetition": "recurring", "date": "2021-10-10" }, 
  { "description": "Freelancer Job",      "amount": "448.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-10-17" },
  { "description": "Android Apps Income",     "amount": "333.23", "type": "income", "repetition": "recurring", "date": "2021-10-10" },
  { "description": "Course Selling",     "amount": "198.23", "type": "income", "repetition": "nonRecurring", "date": "2021-10-10" },
  { "description": "Investiments",     "amount": "119.23", "type": "income", "repetition": "recurring", "date": "2021-10-10" },
  { "description": "Cloth Selling",      "amount": "18.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-10-22" },
  { "description": "Freelancer Site", "amount": "215.23",  "type": "income", "repetition": "nonRecurring",   "date": "2021-10-21" },
  { "description": "iOS Apps Income",      "amount": "265.13",  "type": "income", "repetition": "recurring",   "date": "2021-10-22" },

  { "description": "Freelancer Job",      "amount": "548.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-11-17" },
  { "description": "Salary",     "amount": "1720.52", "type": "income", "repetition": "recurring", "date": "2021-11-10" }, 
  { "description": "Cloth Selling",      "amount": "22.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-11-22" },
  { "description": "iOS Apps Income",      "amount": "156.13",  "type": "income", "repetition": "recurring",   "date": "2021-11-22" },
  { "description": "Freelancer Job",      "amount": "320.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-11-22" },
  { "description": "Freelancer Site", "amount": "122.23",  "type": "income", "repetition": "nonRecurring",   "date": "2021-11-21" },
  { "description": "Investiments",     "amount": "232.23", "type": "income", "repetition": "recurring", "date": "2021-11-10" },
  { "description": "Course Selling",     "amount": "217.23", "type": "income", "repetition": "nonRecurring", "date": "2021-11-10" },
  { "description": "Android Apps Income",     "amount": "129.23", "type": "income", "repetition": "recurring", "date": "2021-11-10" },

  { "description": "Freelancer Job",      "amount": "276.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-12-22" },
  { "description": "Cloth Selling",      "amount": "153.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-12-22" },
  { "description": "Android Apps Income",     "amount": "133.23", "type": "income", "repetition": "recurring", "date": "2021-12-10" },
  { "description": "Freelancer Job",      "amount": "348.13",  "type": "income", "repetition": "nonRecurring",   "date": "2021-12-17" },
  { "description": "Salary",     "amount": "1720.52", "type": "income", "repetition": "recurring", "date": "2021-12-10" }, 
  { "description": "Freelancer Site", "amount": "198.23",  "type": "income", "repetition": "nonRecurring",   "date": "2021-12-21" },
  { "description": "Course Selling",     "amount": "121.23", "type": "income", "repetition": "nonRecurring", "date": "2021-12-10" },
  { "description": "Investiments",     "amount": "165.23", "type": "income", "repetition": "recurring", "date": "2021-12-10" },
  { "description": "iOS Apps Income",      "amount": "177.13",  "type": "income", "repetition": "recurring",   "date": "2021-12-22" },

  { "description": "Freelancer Job",      "amount": "448.13",  "type": "income", "repetition": "nonRecurring",   "date": "2022-01-17" },
  { "description": "Cloth Selling",      "amount": "87.13",  "type": "income", "repetition": "nonRecurring",   "date": "2022-01-22" },
  { "description": "Freelancer Job",      "amount": "327.13",  "type": "income", "repetition": "nonRecurring",   "date": "2022-01-22" },
  { "description": "iOS Apps Income",      "amount": "165.13",  "type": "income", "repetition": "recurring",   "date": "2022-01-22" },
  { "description": "Salary",     "amount": "1720.52", "type": "income", "repetition": "recurring", "date": "2022-01-10" }, 
  { "description": "Course Selling",     "amount": "211.23", "type": "income", "repetition": "nonRecurring", "date": "2022-01-10" },
  { "description": "Android Apps Income",     "amount": "164.23", "type": "income", "repetition": "recurring", "date": "2022-01-10" },
  { "description": "Freelancer Site", "amount": "176.23",  "type": "income", "repetition": "nonRecurring",   "date": "2022-01-21" },
  { "description": "Investiments",     "amount": "122.23", "type": "income", "repetition": "recurring", "date": "2022-01-10" },

  { "description": "Freelancer Job",      "amount": "336.13",  "type": "income", "repetition": "nonRecurring",   "date": "2022-02-17" },
  { "description": "Cloth Selling",      "amount": "22.13",  "type": "income", "repetition": "nonRecurring",   "date": "2022-02-22" },
  { "description": "Course Selling",     "amount": "120.23", "type": "income", "repetition": "nonRecurring", "date": "2022-02-10" },
  { "description": "Freelancer Job",      "amount": "310.13",  "type": "income", "repetition": "nonRecurring",   "date": "2022-02-22" },
  { "description": "Salary",     "amount": "1720.52", "type": "income", "repetition": "recurring", "date": "2022-02-10" }, 
  { "description": "iOS Apps Income",      "amount": "198.13",  "type": "income", "repetition": "recurring",   "date": "2022-02-22" },
  { "description": "Android Apps Income",     "amount": "279.23", "type": "income", "repetition": "recurring", "date": "2022-02-10" },
  { "description": "Freelancer Site", "amount": "177.23",  "type": "income", "repetition": "nonRecurring",   "date": "2022-02-21" },
  { "description": "Investiments",     "amount": "165.23", "type": "income", "repetition": "recurring", "date": "2022-02-10" },

  { "description": "Freelancer Job",      "amount": "452.13",  "type": "income", "repetition": "nonRecurring",   "date": "2022-03-17" },
  { "description": "Freelancer Job",      "amount": "220.13",  "type": "income", "repetition": "nonRecurring",   "date": "2022-03-22" },
  { "description": "Cloth Selling",      "amount": "64.13",  "type": "income", "repetition": "nonRecurring",   "date": "2022-03-22" },
  { "description": "Course Selling",     "amount": "230.23", "type": "income", "repetition": "nonRecurring", "date": "2022-03-10" },
  { "description": "Android Apps Income",     "amount": "254.23", "type": "income", "repetition": "recurring", "date": "2022-03-10" },
  { "description": "iOS Apps Income",      "amount": "227.13",  "type": "income", "repetition": "recurring",   "date": "2022-03-22" },
  { "description": "Salary",     "amount": "1720.52", "type": "income", "repetition": "recurring", "date": "2022-03-10" }, 
  { "description": "Freelancer Site", "amount": "77.23",  "type": "income", "repetition": "nonRecurring",   "date": "2022-03-21" },
  { "description": "Investiments",     "amount": "122.23", "type": "income", "repetition": "recurring", "date": "2022-03-10" },

  { "description": "Freelancer Job",      "amount": "148.13",  "type": "income", "repetition": "nonRecurring",   "date": "2022-04-17" },
  { "description": "Cloth Selling",      "amount": "35.13",  "type": "income", "repetition": "nonRecurring",   "date": "2022-04-22" },
  { "description": "Salary",     "amount": "1720.52", "type": "income", "repetition": "recurring", "date": "2022-04-10" }, 
  { "description": "Freelancer Job",      "amount": "311.13",  "type": "income", "repetition": "nonRecurring",   "date": "2022-04-22" },
  { "description": "Android Apps Income",     "amount": "103.23", "type": "income", "repetition": "recurring", "date": "2022-04-10" },
  { "description": "Course Selling",     "amount": "254.23", "type": "income", "repetition": "nonRecurring", "date": "2022-04-10" },
  { "description": "Freelancer Site", "amount": "221.23",  "type": "income", "repetition": "nonRecurring",   "date": "2022-04-21" },
  { "description": "Investiments",     "amount": "111.23", "type": "income", "repetition": "recurring", "date": "2022-04-10" },
  { "description": "iOS Apps Income",      "amount": "102.13",  "type": "income", "repetition": "recurring",   "date": "2022-04-22" },

  { "description": "Freelancer Job",      "amount": "648.13",  "type": "income", "repetition": "nonRecurring",   "date": "2022-05-17" },
  { "description": "Cloth Selling",      "amount": "25.13",  "type": "income", "repetition": "nonRecurring",   "date": "2022-05-22" },
  { "description": "Android Apps Income",     "amount": "149.23", "type": "income", "repetition": "recurring", "date": "2022-05-10" },
  { "description": "Freelancer Job",      "amount": "320.13",  "type": "income", "repetition": "nonRecurring",   "date": "2022-05-22" },
  { "description": "Course Selling",     "amount": "130.23", "type": "income", "repetition": "nonRecurring", "date": "2022-05-10" },
  { "description": "iOS Apps Income",      "amount": "137.13",  "type": "income", "repetition": "recurring",   "date": "2022-05-22" },
  { "description": "Freelancer Site", "amount": "198.23",  "type": "income", "repetition": "nonRecurring",   "date": "2022-05-21" },
  { "description": "Salary",     "amount": "1750.52", "type": "income", "repetition": "recurring", "date": "2022-05-10" }, 
  { "description": "Investiments",     "amount": "118.23", "type": "income", "repetition": "recurring", "date": "2022-05-10" },

  { "description": "Freelancer Job",      "amount": "348.13",  "type": "income", "repetition": "nonRecurring",   "date": "2022-06-17" },
  { "description": "Cloth Selling",      "amount": "19.13",  "type": "income", "repetition": "nonRecurring",   "date": "2022-06-22" },
  { "description": "Freelancer Job",      "amount": "320.13",  "type": "income", "repetition": "nonRecurring",   "date": "2022-06-22" },
  { "description": "Salary",     "amount": "1750.52", "type": "income", "repetition": "recurring", "date": "2022-06-10" }, 
  { "description": "Android Apps Income",     "amount": "88.23", "type": "income", "repetition": "recurring", "date": "2022-06-10" },
  { "description": "Investiments",     "amount": "188.23", "type": "income", "repetition": "recurring", "date": "2022-06-10" },
  { "description": "iOS Apps Income",      "amount": "98.13",  "type": "income", "repetition": "recurring",   "date": "2022-06-22" },
  { "description": "Course Selling",     "amount": "120.23", "type": "income", "repetition": "nonRecurring", "date": "2022-06-10" },
  { "description": "Freelancer Site", "amount": "96.23",  "type": "income", "repetition": "nonRecurring",   "date": "2022-06-21" },

  { "description": "Freelancer Job",      "amount": "38.13",  "type": "income", "repetition": "nonRecurring",   "date": "2022-07-17" },
  { "description": "Cloth Selling",      "amount": "55.13",  "type": "income", "repetition": "nonRecurring",   "date": "2022-07-22" },
  { "description": "Salary",     "amount": "1750.52", "type": "income", "repetition": "recurring", "date": "2022-07-10" }, 
  { "description": "Freelancer Job",      "amount": "410.13",  "type": "income", "repetition": "nonRecurring",   "date": "2022-07-22" },
  { "description": "iOS Apps Income",      "amount": "137.13",  "type": "income", "repetition": "recurring",   "date": "2022-07-22" },
  { "description": "Investiments",     "amount": "148.23", "type": "income", "repetition": "recurring", "date": "2022-07-10" },
  { "description": "Course Selling",     "amount": "170.23", "type": "income", "repetition": "nonRecurring", "date": "2022-07-10" },
  { "description": "Freelancer Site", "amount": "223.23",  "type": "income", "repetition": "nonRecurring",   "date": "2022-07-21" },
  { "description": "Android Apps Income",     "amount": "249.23", "type": "income", "repetition": "recurring", "date": "2022-07-10" },

  { "description": "Salary",     "amount": "1750.52", "type": "income", "repetition": "recurring", "date": "2022-08-10" }, 
  { "description": "Freelancer Job",      "amount": "275.13",  "type": "income", "repetition": "nonRecurring",   "date": "2022-08-22" },
  { "description": "Cloth Selling",      "amount": "35.13",  "type": "income", "repetition": "nonRecurring",   "date": "2022-08-22" },
  { "description": "iOS Apps Income",      "amount": "211.13",  "type": "income", "repetition": "recurring",   "date": "2022-08-22" },
  { "description": "Freelancer Job",      "amount": "354.13",  "type": "income", "repetition": "nonRecurring",   "date": "2022-08-17" },
  { "description": "Investiments",     "amount": "153.23", "type": "income", "repetition": "recurring", "date": "2022-08-10" },
  { "description": "Course Selling",     "amount": "100.23", "type": "income", "repetition": "nonRecurring", "date": "2022-08-10" },
  { "description": "Android Apps Income",     "amount": "308.23", "type": "income", "repetition": "recurring", "date": "2022-08-10" },
  { "description": "Freelancer Site", "amount": "198.23",  "type": "income", "repetition": "nonRecurring",   "date": "2022-08-21" },
]

  export default income